server:
  port: 0
spring:
  application:
    name: @project.name@
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # 显示ip
    instance-id: ${spring.application.name}:${random.uuid}

# http://cloud.spring.io/spring-cloud-static/Camden.SR7/#_using_ribbon_with_eureka
ribbon:
  eureka:
   enabled: false

stores:
  ribbon:
    listOfServers: localhost:9532